check labels length, trigger when labels updated

diff --git a/.github/workflows/ci-web.yaml b/.github/workflows/ci-web.yaml
--- a/.github/workflows/ci-web.yaml
+++ b/.github/workflows/ci-web.yaml
@@ -1,6 +1,7 @@
 name: Run CI
 on:
   pull_request:
+    types: [opened, synchronize, reopened, labeled, unlabeled]
     paths:
       - '**'
   workflow_dispatch:
@@ -37,6 +38,12 @@ jobs:
         run: |
           yarn install --immutable
           yarn ci
+      
+      - name: Check if PR is labeled
+        if: github.event.pull_request.draft == false && github.event.pull_request.user.login != 'dependabot' && github.event.pull_request.user.login != 'github-actions' && github.event.pull_request.labels[0] == null
+        run: |
+          echo "PR does not have any labels. Failing the job."
+          exit 1
 
       - name: Publish to Chromatic
         if: steps.filter.outputs.components == 'true' && github.event.pull_request.draft == false && !startsWith(github.event.pull_request.head.ref, 'dependabot/')
